name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, sqlite, bcmath, intl, pcntl
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Verify rule mapping
        run: php scripts/verify-rules-map.php

      - name: Run test suite
        run: php artisan test
